### ISSUE TITLE
More informations about failover logical replication_slot

### ISSUE THREAD

**Issue by MathCharton** [EnterpriseDB/pg_failover_slots#10]
Hello to all !
Would it be possible to have more information on how you managed these possible problems:

- Requested WAL segment pg_wal/XXX has already been removed

- It can be unsafe to use the logical slot after promote if replicas physical slot didn’t reach the catalog_xmin of the
logical slot on the old primary

Thanks

**Comment by ashucoek** [comment]
Hi,

Please find my answers below:

Answer to point #1: If the standby does not have the WAL segment needed by the logical slot, then standby will wait for the primary slot catchup.  Kindly check wait_for_primary_slot_catchup() function. Until this happens, the slot will be marked as unsafe (not synchronized) and will be dropped if failover happens.

Answer to point #2: pg_failover_slots does not allow logical WAL Senders to send WAL to its subscribers before it has been sent to the standby. Hence,  the problem logical subscriber getting ahead of standby (new primary - if failover happens) shouldn't occur.

--
With Regards,
Ashutosh Sharma.

**Comment by ashucoek** [comment]
Hi Mathieu,

Please mark this as closed if you are satisfied with the answer.

--
With Regards,
Ashutosh Sharma.
