### ISSUE TITLE
Support of this extension for PostgreSQL 11+

### ISSUE THREAD

**Issue by varun7447** [EnterpriseDB/pg_failover_slots#14]
Can this extension be used with PostgreSQL 11+? The installation documentation has https://www.enterprisedb.com/docs/pg_extensions/pg_failover_slots/installing/ but the github readme says PostgreSQL 11 or higher.

**Comment by BillSmith-EDB** [comment]
Initially we only supported v12+ but since then we have added v11.  Thanks for pointing out the error in the docs.  We'll get this corrected.

**Comment by varun7447** [comment]
Can the extension be used with OSS PostgreSQL? Is it part of the core package? Or need to be installed using a package manager and then install the extension?

**Comment by BillSmith-EDB** [comment]
Documentation has been updated to show v11.

Yes, it can be used with OSS PG. I can't comment if it will be part of core.

**Comment by BillSmith-EDB** [comment]
@PJMODOS @petere i think this can be closed.

**Comment by varun7447** [comment]
I wonder if this can be used during Major version upgrade as a plan to reduce the downtime?

**Comment by petere** [comment]
> I wonder if this can be used during Major version upgrade as a plan to reduce the downtime by not required to recreate the replication slots after the restart or upgrade.?

pg_failover_slots syncs replication slots across physical replication, which have to be of the same major version. So I don't see how it would be applicable.
