### ISSUE TITLE
Missing control file when installed via apt postgresql repo

### ISSUE THREAD

**Issue by sjuls** [EnterpriseDB/pg_failover_slots#15]
From a fresh postgresql, installing pg_failover_slots does not install a control file, leading `CREATE EXTENSION pg_failover_slots;` to fail.

To reproduce:
```
$ docker run -it -u=0 --entrypoint /bin/bash postgres:15
# apt update
# apt install postgresql-15-pg-failover-slots
# find / -name pg_failover_slots # verify library installed - finds the library
/usr/lib/postgresql/15/lib/bitcode/pg_failover_slots
# find / -name pg_failover_slots.control # verify control file installed - finds no control file
```

**Comment by petere** [comment]
pg_failover_slots is not an "extension" in the sense that you activate using CREATE EXTENSION. It is a module that you add to shared_preload_libraries. I see that the README uses the term extension in an arguably ambiguous way. Maybe that should be improved.

**Comment by sjuls** [comment]
Ah, I see - Thanks for the clarification!
